name: cleaninventory
main: cleaninventory\Main
author: OmgBossinator
version: 1.0
api: [3.0.0, 3.1.0, 4.0.0]

commands:
 clean:
  description: "Clean all your inventory"
  permission: clearinventory.main.command
